services:
  wakapi:
    build: .
    init: true
    ports:
      - ${WAKA_PORT:-4002}:3000
    restart: unless-stopped
    environment:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      # WAKAPI_DB_PASSWORD_FILE: "/run/secrets/db_password"       # alternatively, set WAKAPI_DB_PASSWORD directly without the use of secrets
      # WAKAPI_PASSWORD_SALT_FILE: "/run/secrets/password_salt"   # alternatively, set WAKAPI_PASSWORD_SALT directly without the use of secrets
      # WAKAPI_MAIL_SMTP_PASS_FILE: "/run/secrets/smtp_pass"      # alternatively, set WAKAPI_MAIL_SMTP_PASS directly without the use of secrets
      WAKAPI_DB_PASSWORD: ${WAKAPI_DB_PASSWORD:?Var WAKAPI_DB_PASSWORD not set}
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT:?Var WAKAPI_PASSWORD_SALT not set}
      WAKAPI_MAIL_SMTP_PASS: ${WAKAPI_MAIL_SMTP_PASS:?Var WAKAPI_MAIL_SMTP_PASS not set}

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: ${WAKAPI_DB_PASSWORD:?Var WAKAPI_DB_PASSWORD not set}        # alternatively, set POSTGRES_PASSWORD directly without the use of secrets
      POSTGRES_DB: "wakapi"
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data

volumes:
  wakapi-db-data: {}
